#!/usr/bin/env ruby

require 'rubygems'
require 'icmp4em'
require 'eventmachine'
require 'riemann/client'
require 'socket'

class RiemannPuppetPing

  def initialize
    path = ARGV[0] || ENV["RPP_CONFIG"] || "/etc/rpp.conf"

    @reports_dir = []
    @retries = 3
    @timeout = 2
    @tags = []
    @ttl = 60
    @host = "localhost"
    @port = 5555
    @interval = 30

    File.open path do |f|
      f.each_line.map{|l| l.chomp.sub(/#.*$/,"").strip}.each do |l|
        next if (l =~ /^$/)

        (directive, val) = l.split("=", 2).map{|x| x.strip.downcase}

        case directive.to_sym
        when :reports_dir
          (reports_dir,tag) = val.split(/:/)
          @reports_dir << {:dir => reports_dir, :tag => tag}
        when :retries
          @retries = val.to_i
        when :timeout
          @timeout = val.to_i
        when :tags
          @tags << val
        when :riemann_host
          @host = val
        when :riemann_port
          @port = val
        end
      end
    end

    @client = Riemann::Client.new :host => @host, :port => @port
  end

  def riemann_send host, success, description, tag=nil
    tags = @tags
    tags = @tags + [tag] if tag
    @client << {:service => "ping",
                :metric => success ? 1 : 0,
                :state => success ? "ok" : "critical",
                :ttl => @ttl,
		:tags => tags,
		:host => host,
		:description => description}
  end

  def ping_success entry
    riemann_send(entry[:host].split(".").first(), true, "ping OK", entry[:tag])
  end

  def ping_failure entry, e
    riemann_send(entry[:host].split(".").first(), false, "ping failure: #{e}", entry[:tag])
  end

  def dir_list()
    files = @reports_dir.map do |entry|
      Dir.chdir(entry[:dir]) do
        entries = Dir.entries(".").reject do |x|
          x == "." or x == ".." or not File.directory? x
        end
        entries.map{ |x| {:host => x, :tag => entry[:tag]}}
      end
    end
    files.flatten
  end

  def pingable? host
    begin
      Socket.getaddrinfo(host, nil)
      true
    rescue
      false
    end
  end

  def ping_everyone(entries)
    manager = ICMP4EM::Manager.new :retries => @retries, :timeout => @timeout
    entries.each do |entry|
      next unless pingable? entry[:host]
      begin
        request = manager.ping entry[:host]
        request.callback { ping_success entry }
        request.errback { |e| ping_failure entry, e }
      rescue
        puts "could not add host: #{host}"
      end
    end
  end

  def serve_forever
    EM.run do
      ping_everyone(dir_list)
      EM.add_periodic_timer(@interval) do
        ping_everyone(dir_list)
      end
    end
  end
end

rpp = RiemannPuppetPing.new
rpp.serve_forever
